[package]
name = "db-data"
version = "0.1.0"
edition = "2021"

[dependencies]
postgres = "0.19.7"
tokio = { version = "1.38.0", features = ["full"] }
sqlx = {version="0.7.4", features=["runtime-tokio-rustls", "postgres"]}
